#:schema https://yazi-rs.github.io/schemas/yazi.json

[opener]
edit = [
	{ run = '${EDITOR:-nvim} %s', desc = "$EDITOR", block = true, for = "unix" },
]

open = [
	{ run = 'xdg-open %s1', desc = "Open", for = "linux" },
]

reveal = [
	{ run = 'xdg-open %d1', desc = "Reveal", for = "linux" },
	{ run = '''clear; exiftool %s1; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
]

extract = [
	{ run = 'ya pub extract --list %s', desc = "Extract here", for = "unix" },
]

play = [
	{ run = 'mpv --force-window %s', orphan = true, desc = "Play", for = "unix" },
	{ run = '''mediainfo %s1; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]

[pick]
open_title  = "Open with:"
open_origin = "hovered"
open_offset = [0, 1, 50, 7]
