[Appearance]
color_scheme_path=/usr/share/qt6ct/colors/darker.conf
custom_palette=true
icon_theme=Adwaita
standard_dialogs=default
style=Fusion

[Fonts]
fixed="Iosevka Nerd Font Mono,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
general="Iosevka Nerd Font,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
