source = $XDG_CACHE_HOME/hyprland-dots/active-theme/hyprlock.conf

general {
  hide_cursor = false
  ignore_empty_input = true
}

background {
  monitor =
  path = $XDG_CACHE_HOME/hyprland-dots/active-theme/wallpaper
  blur_size = 4
  blur_passes = 2
  noise = 0.02
  contrast = 0.8916
  brightness = 0.5172
  vibrancy = 0.1696
  vibrancy_darkness = 0.0
  color = $border_inactive
}

image {
  path = $XDG_CONFIG_HOME/hyprland-dots/assets-profile/bored.jpg
  size = 96
  position = -180, 0
  halign = center
  valign = center
  rounding = 96
  border_size = 3
  border_color = $color2
}

label {
  text = Welcome, $USER...
  font_family = Iosevka Nerd Font
  font_size = 25
  halign = center
  valign = center
  position = 75, 0
  color = $border_active
}

label {
  monitor =
  text = $TIME
  color = $border_active
  font_size = 100
  font_family = Iosevka Nerd Font Mono
  position = 750, 40%
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:60000] date +"%A, %B %d"
  color = $border_active
  font_size = 25
  font_family = Iosevka Nerd Font Mono
  position = 750, 32%
}

input-field {
  monitor =
  size = 200, 50
  outline_thickness = 3
  dots_size = 0.33
  dots_spacing = 0.15
  dots_center = true
  dots_rounding = -1
  outer_color = $focused2
  inner_color = $border_inactive
  font_color = $border_active
  fade_on_empty = true
  fade_timeout = 1000
  placeholder_text = <i></i>
  hide_input = false
  rounding = 8
  check_color = $focused
  fail_color = $urgent
  fail_text = Invalid Password
  fail_transition = 300
  capslock_color = -1
  numlock_color = -1
  bothlock_color = -1
  invert_numlock = false
  swap_font_color = false
  position = 0, -35%
  halign = center
  valign = center
}

label {
  monitor =
  text = $LAYOUT
  color = $border_active
  font_size = 14
  font_family = Iosevka Nerd Font
  position = 0, -40%
  halign = center
  valign = center
}
