hl.on("hyprland.start", function()
  hl.exec_cmd("dbus-update-activation-environment --systemd --all")
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("nm-applet --indicator")
  hl.exec_cmd([["${XDG_CONFIG_HOME:-$HOME/.config}/swaync/start.sh"]])
  hl.exec_cmd("wl-paste --watch cliphist store")
  hl.exec_cmd("hypridle")
  hl.exec_cmd([["${XDG_CONFIG_HOME:-$HOME/.config}/waybar/scripts/theme-switcher.sh" restore]])
  hl.exec_cmd("waybar")
  hl.exec_cmd("blueman-applet")
end)
