#!/usr/bin/env python3

"""Render Cassan's shared palette into component-native theme files."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from validate_toml import PALETTE_PATH, REPO, load, validate_palette


OUTPUTS = {
    REPO / "btop" / "themes" / "nighthowler.theme": "btop",
    REPO / "cava" / "themes" / "nighthowler": "cava",
    REPO / "fastfetch" / "config.jsonc": "fastfetch",
    REPO / "firefox" / "cassan-nighthowler.css": "firefox_chrome",
    REPO / "firefox" / "cassan-nighthowler-content.css": "firefox_content",
    REPO / "hypr" / "hyprlock.conf": "hyprlock",
    REPO / "hypr" / "theme.lua": "hypr",
    REPO / "hypr" / "hyprpaper.conf": "hyprpaper",
    REPO / "kitty" / "theme.conf": "kitty",
    REPO / "swaync" / "theme.css": "swaync",
    REPO / "spicetify" / "Cassan-Nighthowler" / "color.ini": "spicetify_colors",
    REPO / "spicetify" / "Cassan-Nighthowler" / "user.css": "spicetify_css",
    REPO / "vesktop" / "Cassan-Nighthowler.theme.css": "vesktop",
    REPO / "waybar" / "theme.css": "gtk",
    REPO / "wofi" / "theme.css": "gtk",
    REPO / "wofi" / "style.css": "wofi",
    REPO / "yazi" / "theme.toml": "yazi",
}

WOFI_STYLE_TEMPLATE = REPO / "wofi" / "style.template.css"


def resolved_roles(palette: dict) -> dict[str, str]:
    colors = palette["colors"]
    return {name: colors[color_name] for name, color_name in palette["roles"].items()}


def without_hash(color: str) -> str:
    return color.removeprefix("#")


def alpha_hex(opacity: float) -> str:
    return f"{round(opacity * 255):02X}"


def hypr_rgba(color: str, opacity: float = 1.0) -> str:
    return f"rgba({without_hash(color)}{alpha_hex(opacity)})"


def rgb_triplet(color: str) -> str:
    value = without_hash(color)
    return ", ".join(str(int(value[index : index + 2], 16)) for index in (0, 2, 4))


def gtk_color(color: str) -> str:
    """Return a GTK CSS color, converting unsupported eight-digit hex values."""
    value = without_hash(color)
    if len(value) == 6:
        return color

    red, green, blue, alpha = (
        int(value[index : index + 2], 16) for index in (0, 2, 4, 6)
    )
    alpha_value = f"{alpha / 255:.3f}".rstrip("0").rstrip(".")
    return f"rgba({red}, {green}, {blue}, {alpha_value})"


def lua_bool(value: bool) -> str:
    return str(value).lower()


def render_hypr(palette: dict) -> str:
    colors = palette["colors"]
    roles = resolved_roles(palette)
    typography = palette["typography"]
    geometry = palette["geometry"]
    animation = palette["animation"]

    lines = [
        "-- Generated by scripts/render_theme.py from assets/nighthowler/palette.toml.",
        "-- Do not edit this file directly.",
        "",
        "return {",
        f'  name = "{palette["name"]}",',
        f'  slug = "{palette["slug"]}",',
        "  colors = {",
    ]

    for name, value in sorted(colors.items()):
        if name == "transparent":
            continue
        lines.append(f'    {name} = "rgba({without_hash(value)}ff)",')

    lines.extend(["  },", "  roles = {"])
    for name, value in sorted(roles.items()):
        lines.append(f'    {name} = "rgba({without_hash(value)}ff)",')

    lines.extend(
        [
            "  },",
            "  geometry = {",
            f"    border = {geometry['border_px']},",
            f"    rounding = {geometry['rounding_px']},",
            f"    gaps_in = {geometry['gap_inner_px']},",
            f"    gaps_out = {geometry['gap_outer_px']},",
            f"    opacity = {geometry['opacity']},",
            f"    blur_enabled = {lua_bool(geometry['blur_enabled'])},",
            f"    shadow_enabled = {lua_bool(geometry['shadow_enabled'])},",
            f"    shadow_range = {geometry['shadow_blur_px']},",
            f"    shadow_opacity = {geometry['shadow_opacity']},",
            f'    shadow_color = "rgba(000000{alpha_hex(geometry["shadow_opacity"])})",',
            "  },",
            "  animation = {",
            f"    fast_ds = {animation['duration_fast_ms'] / 100},",
            f"    normal_ds = {animation['duration_normal_ms'] / 100},",
            f"    slow_ds = {animation['duration_slow_ms'] / 100},",
            "  },",
            "  typography = {",
            f'    desktop = "{typography["desktop_font"]}",',
            f'    terminal = "{typography["terminal_font"]}",',
            f"    bar_size = {typography['bar_size_px']},",
            "  },",
            "  wallpaper = {",
            f'    relative_path = "assets/{palette["slug"]}/{palette["wallpaper"]["filename"]}",',
            f'    fit_mode = "{palette["wallpaper"]["fit"]}",',
            "  },",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def render_hyprpaper(palette: dict) -> str:
    wallpaper = palette["wallpaper"]
    path = f'~/.config/cassan/assets/{palette["slug"]}/{wallpaper["filename"]}'
    return "\n".join(
        [
            "# Generated by scripts/render_theme.py from assets/nighthowler/palette.toml.",
            "# Do not edit this file directly.",
            "",
            "wallpaper {",
            "  monitor =",
            f"  path = {path}",
            f"  fit_mode = {wallpaper['fit']}",
            "}",
            "",
            "splash = false",
            "ipc = true",
            "",
        ]
    )


def render_hyprlock(palette: dict) -> str:
    """Render a low-overhead lock screen that preserves the wallpaper subject."""
    colors = palette["colors"]
    roles = resolved_roles(palette)
    typography = palette["typography"]
    geometry = palette["geometry"]
    wallpaper = palette["wallpaper"]
    wallpaper_path = (
        f'~/.config/cassan/assets/{palette["slug"]}/{wallpaper["filename"]}'
    )

    lines = [
        "# Generated by scripts/render_theme.py from assets/nighthowler/palette.toml.",
        "# Do not edit this file directly.",
        "",
        "general {",
        "  hide_cursor = true",
        "  ignore_empty_input = true",
        "  immediate_render = true",
        "  text_trim = true",
        "  fractional_scaling = 2",
        "  fail_timeout = 1600",
        "}",
        "",
        "animations {",
        "  enabled = true",
        "  bezier = cassan, 0.2, 0.0, 0.0, 1.0",
        "  animation = fadeIn, 1, 3, cassan",
        "  animation = fadeOut, 1, 3, cassan",
        "  animation = inputFieldColors, 1, 2, cassan",
        "  animation = inputFieldDots, 1, 2, cassan",
        "}",
        "",
        "background {",
        "  monitor =",
        f"  path = {wallpaper_path}",
        f"  color = {hypr_rgba(roles['background'])}",
        "  blur_passes = 0",
        "  noise = 0.0",
        "  contrast = 1.0",
        "  brightness = 0.72",
        "  vibrancy = 0.0",
        "  vibrancy_darkness = 0.0",
        "  zindex = -1",
        "}",
        "",
        "shape {",
        "  monitor =",
        "  size = 22%, 34%",
        f"  color = {hypr_rgba(roles['panel'])}",
        f"  rounding = {geometry['rounding_px']}",
        f"  border_size = {geometry['border_px']}",
        f"  border_color = {hypr_rgba(roles['focus_inactive'])}",
        "  shadow_passes = 1",
        f"  shadow_size = {geometry['shadow_blur_px']}",
        f"  shadow_color = {hypr_rgba('#000000', geometry['shadow_opacity'])}",
        "  position = -3%, 0",
        "  halign = right",
        "  valign = center",
        "  zindex = 1",
        "}",
        "",
        "label {",
        "  monitor =",
        "  text = CASSAN // LOCKED",
        "  text_align = right",
        f"  color = {hypr_rgba(roles['focus'])}",
        f"  font_size = {typography['bar_size_px']}",
        f"  font_family = {typography['desktop_font']}",
        "  position = -5%, 12%",
        "  halign = right",
        "  valign = center",
        "  zindex = 2",
        "}",
        "",
        "label {",
        "  monitor =",
        "  text = $TIME",
        "  text_align = right",
        f"  color = {hypr_rgba(roles['text'])}",
        "  font_size = 64",
        f"  font_family = {typography['desktop_font']}",
        "  position = -5%, 5%",
        "  halign = right",
        "  valign = center",
        "  zindex = 2",
        "}",
        "",
        "label {",
        "  monitor =",
        "  text = cmd[update:60000] date '+%A // %d %B'",
        "  text_align = right",
        f"  color = {hypr_rgba(roles['text_secondary'])}",
        "  font_size = 15",
        f"  font_family = {typography['desktop_font']}",
        "  position = -5%, -1%",
        "  halign = right",
        "  valign = center",
        "  zindex = 2",
        "}",
        "",
        "label {",
        "  monitor =",
        "  text = USER // $USER",
        "  text_align = right",
        f"  color = {hypr_rgba(roles['text_muted'])}",
        "  font_size = 14",
        f"  font_family = {typography['desktop_font']}",
        "  position = -5%, -6%",
        "  halign = right",
        "  valign = center",
        "  zindex = 2",
        "}",
        "",
        "input-field {",
        "  monitor =",
        "  size = 18%, 5%",
        f"  outline_thickness = {geometry['border_px']}",
        "  dots_size = 0.22",
        "  dots_spacing = 0.24",
        "  dots_center = true",
        "  dots_rounding = 0",
        f"  outer_color = {hypr_rgba(roles['focus'])}",
        f"  inner_color = {hypr_rgba(roles['panel_alternate'])}",
        f"  font_color = {hypr_rgba(roles['text'])}",
        f"  font_family = {typography['desktop_font']}",
        "  fade_on_empty = false",
        f'  placeholder_text = <span foreground="##{without_hash(roles["text_muted"])}">PASSWORD</span>',
        "  hide_input = false",
        f"  rounding = {geometry['rounding_px']}",
        f"  check_color = {hypr_rgba(colors['sage'])}",
        f'  check_text = <span foreground="##{without_hash(colors["sage"])}">VERIFYING</span>',
        f"  fail_color = {hypr_rgba(roles['urgent'])}",
        f'  fail_text = <span foreground="##{without_hash(roles["urgent"])}">AUTHENTICATION FAILED // $ATTEMPTS</span>',
        f"  capslock_color = {hypr_rgba(roles['warm_accent'])}",
        "  position = -5%, -11.5%",
        "  halign = right",
        "  valign = center",
        "  zindex = 2",
        "}",
        "",
        "label {",
        "  monitor =",
        "  text = ENTER TO UNLOCK // ESC TO CLEAR",
        "  text_align = right",
        f"  color = {hypr_rgba(roles['text_muted'])}",
        "  font_size = 11",
        f"  font_family = {typography['desktop_font']}",
        "  position = -5%, -16%",
        "  halign = right",
        "  valign = center",
        "  zindex = 2",
        "}",
        "",
    ]
    return "\n".join(lines)


def render_gtk_theme(palette: dict) -> str:
    colors = palette["colors"]
    roles = resolved_roles(palette)
    geometry = palette["geometry"]

    lines = [
        "/* Generated by scripts/render_theme.py from assets/nighthowler/palette.toml.",
        " * Do not edit this file directly.",
        " */",
        "",
    ]

    for name, value in sorted(colors.items()):
        css_name = name.replace("_", "-")
        lines.append(f"@define-color cassan-color-{css_name} {gtk_color(value)};")

    lines.append("")
    for name, value in sorted(roles.items()):
        css_name = name.replace("_", "-")
        lines.append(f"@define-color cassan-{css_name} {gtk_color(value)};")

    lines.extend(
        [
            f"@define-color cassan-shadow rgba(0, 0, 0, {geometry['shadow_opacity']});",
            "",
        ]
    )
    return "\n".join(lines)


def render_kitty(palette: dict) -> str:
    colors = palette["colors"]
    terminal = {
        name: colors[color_name] for name, color_name in palette["terminal"].items()
    }
    roles = resolved_roles(palette)
    typography = palette["typography"]

    lines = [
        "# Generated by scripts/render_theme.py from assets/nighthowler/palette.toml.",
        "# Do not edit this file directly.",
        "",
        f"font_family {typography['terminal_font']}",
        f"font_size {typography['terminal_size_pt']}.0",
        "",
        f"foreground {terminal['foreground']}",
        f"background {terminal['background']}",
        f"cursor {terminal['cursor']}",
        f"cursor_text_color {terminal['cursor_text']}",
        f"selection_foreground {terminal['selection_foreground']}",
        f"selection_background {terminal['selection_background']}",
        f"url_color {terminal['url']}",
        "",
        f"active_border_color {roles['focus']}",
        f"inactive_border_color {roles['panel_alternate']}",
        f"bell_border_color {roles['urgent']}",
        f"active_tab_foreground {roles['background']}",
        f"active_tab_background {roles['focus']}",
        f"inactive_tab_foreground {roles['text_muted']}",
        f"inactive_tab_background {roles['panel']}",
        f"tab_bar_background {roles['background']}",
        "",
    ]

    for index in range(16):
        lines.append(f"color{index} {terminal[f'color{index}']}")
    lines.append("")
    return "\n".join(lines)


def render_wofi(palette: dict) -> str:
    """Render one self-contained stylesheet because Wofi loses import paths."""
    template = WOFI_STYLE_TEMPLATE.read_text(encoding="utf-8")
    if "@import" in template:
        raise ValueError("wofi/style.template.css must not contain relative imports")
    return render_gtk_theme(palette).rstrip() + "\n\n" + template


def render_swaync(palette: dict) -> str:
    roles = resolved_roles(palette)
    geometry = palette["geometry"]
    animation = palette["animation"]
    typography = palette["typography"]

    gtk_colors = render_gtk_theme(palette).rstrip()
    lines = [
        gtk_colors,
        "",
        ":root {",
        f"  --cc-bg: {roles['panel']};",
        f"  --noti-border-color: {roles['focus_inactive']};",
        f"  --noti-bg: {rgb_triplet(roles['panel'])};",
        f"  --noti-bg-alpha: {geometry['opacity']};",
        f"  --noti-bg-darker: {roles['background']};",
        f"  --noti-bg-hover: {roles['panel_alternate']};",
        f"  --noti-bg-focus: rgba({rgb_triplet(roles['focus'])}, 0.18);",
        f"  --noti-close-bg: {roles['panel_alternate']};",
        f"  --noti-close-bg-hover: {roles['focus_inactive']};",
        f"  --text-color: {roles['text']};",
        f"  --text-color-disabled: {roles['text_muted']};",
        f"  --bg-selected: {roles['focus']};",
        f"  --border: 1px solid {roles['focus_inactive']};",
        f"  --border-radius: {geometry['rounding_px']}px;",
        "  --notification-shadow: none;",
        "  --notification-icon-size: 48px;",
        "  --notification-group-icon-size: 24px;",
        f"  --font-size-body: {typography['launcher_size_px']}px;",
        f"  --font-size-summary: {typography['bar_size_px']}px;",
        f"  --mpris-album-art-overlay: rgba({rgb_triplet(roles['background'])}, 0.90);",
        f"  --mpris-button-hover: {roles['panel_alternate']};",
        "  --mpris-album-art-icon-size: 72px;",
        "  --mpris-album-art-shadow: none;",
        "  --widget-volume-row-icon-size: 20px;",
        f"  --hover-tranistion: background {animation['duration_fast_ms']}ms ease-out;",
        f"  --group-collapse-tranistion: opacity {animation['duration_normal_ms']}ms ease-out;",
        "}",
        "",
    ]
    return "\n".join(lines)


def render_yazi(palette: dict) -> str:
    """Render Yazi's UI chrome while retaining its maintained file-type defaults."""
    colors = palette["colors"]
    roles = resolved_roles(palette)

    lines = [
        "#:schema https://yazi-rs.github.io/schemas/theme.json",
        "# Generated by scripts/render_theme.py from assets/nighthowler/palette.toml.",
        "# Do not edit this file directly.",
        "",
        "[app]",
        f'overall = {{ bg = "{roles["background"]}" }}',
        "",
        "[mgr]",
        f'cwd = {{ fg = "{roles["focus"]}", bold = true }}',
        f'find_keyword = {{ fg = "{roles["warm_accent"]}", bold = true, underline = true }}',
        f'find_position = {{ fg = "{roles["focus"]}", italic = true }}',
        f'symlink_target = {{ fg = "{colors["teal"]}", italic = true }}',
        f'marker_copied = {{ fg = "{colors["sage"]}", bg = "{colors["sage"]}" }}',
        f'marker_cut = {{ fg = "{roles["urgent"]}", bg = "{roles["urgent"]}" }}',
        f'marker_marked = {{ fg = "{colors["teal"]}", bg = "{colors["teal"]}" }}',
        f'marker_selected = {{ fg = "{roles["warm_accent"]}", bg = "{roles["warm_accent"]}" }}',
        'marker_symbol = "│"',
        f'count_copied = {{ fg = "{roles["background"]}", bg = "{colors["sage"]}", bold = true }}',
        f'count_cut = {{ fg = "{roles["background"]}", bg = "{roles["urgent"]}", bold = true }}',
        f'count_selected = {{ fg = "{roles["background"]}", bg = "{roles["warm_accent"]}", bold = true }}',
        'border_symbol = "│"',
        f'border_style = {{ fg = "{roles["focus_inactive"]}" }}',
        "",
        "[tabs]",
        f'active = {{ fg = "{roles["background"]}", bg = "{roles["focus"]}", bold = true }}',
        f'inactive = {{ fg = "{roles["text_muted"]}", bg = "{roles["panel_alternate"]}" }}',
        'sep_inner = { open = " ", close = " " }',
        'sep_outer = { open = "", close = "" }',
        "",
        "[mode]",
        f'normal_main = {{ fg = "{roles["background"]}", bg = "{roles["focus"]}", bold = true }}',
        f'normal_alt = {{ fg = "{roles["text"]}", bg = "{roles["panel_alternate"]}" }}',
        f'select_main = {{ fg = "{roles["background"]}", bg = "{roles["warm_accent"]}", bold = true }}',
        f'select_alt = {{ fg = "{roles["warm_accent"]}", bg = "{roles["panel_alternate"]}" }}',
        f'unset_main = {{ fg = "{roles["background"]}", bg = "{roles["text_muted"]}", bold = true }}',
        f'unset_alt = {{ fg = "{roles["text_muted"]}", bg = "{roles["panel_alternate"]}" }}',
        "",
        "[indicator]",
        f'parent = {{ fg = "{roles["text_muted"]}" }}',
        f'current = {{ fg = "{roles["focus"]}" }}',
        f'preview = {{ fg = "{roles["warm_accent"]}" }}',
        "",
        "[status]",
        f'overall = {{ fg = "{roles["text"]}", bg = "{roles["panel"]}" }}',
        'sep_left = { open = "", close = "" }',
        'sep_right = { open = "", close = "" }',
        f'perm_sep = {{ fg = "{roles["text_muted"]}" }}',
        f'perm_type = {{ fg = "{roles["focus"]}" }}',
        f'perm_read = {{ fg = "{colors["sage"]}" }}',
        f'perm_write = {{ fg = "{roles["warm_accent"]}" }}',
        f'perm_exec = {{ fg = "{roles["urgent"]}" }}',
        f'progress_label = {{ fg = "{roles["background"]}", bold = true }}',
        f'progress_normal = {{ fg = "{roles["focus"]}", bg = "{roles["panel_alternate"]}" }}',
        f'progress_error = {{ fg = "{roles["urgent"]}", bg = "{roles["panel_alternate"]}" }}',
        "",
        "[which]",
        "cols = 3",
        f'mask = {{ bg = "{roles["background"]}" }}',
        f'cand = {{ fg = "{roles["focus"]}", bold = true }}',
        f'rest = {{ fg = "{roles["text"]}" }}',
        f'desc = {{ fg = "{roles["text_muted"]}" }}',
        'separator = " 󰁔 "',
        f'separator_style = {{ fg = "{roles["focus_inactive"]}" }}',
        "",
        "[confirm]",
        f'border = {{ fg = "{roles["focus"]}" }}',
        f'title = {{ fg = "{roles["focus"]}", bold = true }}',
        f'body = {{ fg = "{roles["text"]}" }}',
        f'list = {{ fg = "{roles["text_secondary"]}" }}',
        f'btn_yes = {{ fg = "{roles["background"]}", bg = "{colors["sage"]}", bold = true }}',
        f'btn_no = {{ fg = "{roles["background"]}", bg = "{roles["urgent"]}", bold = true }}',
        "",
        "[spot]",
        f'border = {{ fg = "{roles["focus"]}" }}',
        f'title = {{ fg = "{roles["focus"]}", bold = true }}',
        f'tbl_col = {{ fg = "{roles["text_secondary"]}" }}',
        f'tbl_cell = {{ fg = "{roles["warm_accent"]}" }}',
        "",
        "[notify]",
        f'title_info = {{ fg = "{colors["teal"]}" }}',
        f'title_warn = {{ fg = "{roles["warm_accent"]}" }}',
        f'title_error = {{ fg = "{roles["urgent"]}" }}',
        'icon_info = ""',
        'icon_warn = ""',
        'icon_error = ""',
        "",
        "[pick]",
        f'border = {{ fg = "{roles["focus"]}" }}',
        f'active = {{ fg = "{roles["focus"]}", bold = true }}',
        f'inactive = {{ fg = "{roles["text_muted"]}" }}',
        "",
        "[input]",
        f'border = {{ fg = "{roles["focus"]}" }}',
        f'title = {{ fg = "{roles["focus"]}", bold = true }}',
        f'value = {{ fg = "{roles["text"]}" }}',
        f'selected = {{ fg = "{roles["background"]}", bg = "{roles["focus"]}" }}',
        "",
        "[cmp]",
        f'border = {{ fg = "{roles["focus"]}" }}',
        f'active = {{ fg = "{roles["focus"]}", bold = true }}',
        f'inactive = {{ fg = "{roles["text_muted"]}" }}',
        'icon_file = ""',
        'icon_folder = ""',
        'icon_command = ""',
        "",
        "[tasks]",
        f'border = {{ fg = "{roles["focus"]}" }}',
        f'title = {{ fg = "{roles["focus"]}", bold = true }}',
        f'hovered = {{ fg = "{roles["background"]}", bg = "{roles["focus"]}" }}',
        "",
        "[help]",
        f'on = {{ fg = "{roles["focus"]}" }}',
        f'run = {{ fg = "{roles["warm_accent"]}" }}',
        f'desc = {{ fg = "{roles["text_secondary"]}" }}',
        f'hovered = {{ fg = "{roles["background"]}", bg = "{roles["focus"]}", bold = true }}',
        f'footer = {{ fg = "{roles["text_muted"]}" }}',
        "",
    ]
    return "\n".join(lines)


def render_fastfetch(palette: dict) -> str:
    """Render a portable Fastfetch view with themed Arch Linux ASCII art."""
    roles = resolved_roles(palette)

    config = {
        "$schema": "https://raw.githubusercontent.com/fastfetch-cli/fastfetch/2.67.1/doc/json_schema.json",
        "logo": {
            "type": "builtin",
            "source": "arch",
            "color": {"1": roles["focus"], "2": roles["text"]},
            "padding": {"top": 1, "left": 1, "right": 3},
            "printRemaining": True,
            "position": "left",
        },
        "display": {
            "separator": "  ",
            "color": {
                "keys": roles["focus"],
                "title": roles["focus"],
                "output": roles["text"],
                "separator": roles["focus_inactive"],
            },
        },
        "modules": [
            "title",
            "separator",
            {"type": "os", "key": " OS"},
            {"type": "host", "key": "󰌢 Host"},
            {"type": "kernel", "key": "󰌽 Kernel"},
            {"type": "packages", "key": "󰏖 Packages"},
            {"type": "shell", "key": " Shell"},
            {"type": "wm", "key": " Desktop"},
            {"type": "terminal", "key": " Terminal"},
            {"type": "terminalfont", "key": " Font"},
            {"type": "cpu", "key": " CPU"},
            {"type": "gpu", "key": "󰍛 GPU"},
            {"type": "memory", "key": "󰘚 Memory"},
            {"type": "battery", "key": "󰁹 Battery"},
            {"type": "uptime", "key": "󰅐 Uptime"},
            {"type": "media", "key": " Playing"},
            "break",
            "colors",
        ],
    }
    return json.dumps(config, indent=2, ensure_ascii=False) + "\n"


def render_cava(palette: dict) -> str:
    """Render Cava's switchable color theme from the shared palette."""
    colors = palette["colors"]
    roles = resolved_roles(palette)

    lines = [
        "# Generated by scripts/render_theme.py from assets/nighthowler/palette.toml.",
        "# Do not edit this file directly.",
        "",
        "[color]",
        f"background = '{roles['background']}'",
        f"foreground = '{roles['focus']}'",
        "gradient = 1",
        f"gradient_color_1 = '{roles['focus_inactive']}'",
        f"gradient_color_2 = '{roles['focus']}'",
        f"gradient_color_3 = '{colors['bright_orchid']}'",
        f"gradient_color_4 = '{colors['teal']}'",
        f"gradient_color_5 = '{colors['sage']}'",
        f"gradient_color_6 = '{roles['warm_accent']}'",
        "",
    ]
    return "\n".join(lines)


def render_btop(palette: dict) -> str:
    """Render btop's resource monitor colors from the shared palette."""
    colors = palette["colors"]
    roles = resolved_roles(palette)

    theme = {
        "main_bg": roles["background"],
        "main_fg": roles["text"],
        "title": roles["text_secondary"],
        "hi_fg": roles["focus"],
        "selected_bg": roles["focus"],
        "selected_fg": roles["background"],
        "inactive_fg": roles["text_muted"],
        "graph_text": roles["text_secondary"],
        "meter_bg": roles["panel_alternate"],
        "proc_misc": colors["teal"],
        "cpu_box": roles["focus"],
        "mem_box": colors["teal"],
        "net_box": colors["sage"],
        "proc_box": roles["warm_accent"],
        "div_line": roles["focus_inactive"],
        "temp_start": colors["sage"],
        "temp_mid": roles["warm_accent"],
        "temp_end": roles["urgent"],
        "cpu_start": roles["focus_inactive"],
        "cpu_mid": roles["focus"],
        "cpu_end": colors["bright_orchid"],
        "free_start": colors["teal"],
        "free_mid": colors["sage"],
        "free_end": colors["bright_sage"],
        "cached_start": colors["sky"],
        "cached_mid": colors["teal"],
        "cached_end": colors["bright_teal"],
        "available_start": roles["focus_inactive"],
        "available_mid": roles["focus"],
        "available_end": colors["bright_orchid"],
        "used_start": roles["warm_accent"],
        "used_mid": colors["bright_marigold"],
        "used_end": roles["urgent"],
        "download_start": colors["sky"],
        "download_mid": colors["teal"],
        "download_end": colors["bright_teal"],
        "upload_start": roles["focus_inactive"],
        "upload_mid": roles["focus"],
        "upload_end": colors["bright_orchid"],
        "process_start": colors["sage"],
        "process_mid": roles["warm_accent"],
        "process_end": roles["urgent"],
    }
    lines = [
        "# Generated by scripts/render_theme.py from assets/nighthowler/palette.toml.",
        "# Do not edit this file directly.",
        "",
    ]
    lines.extend(f'theme[{name}]="{value}"' for name, value in theme.items())
    lines.append("")
    return "\n".join(lines)


def render_firefox_chrome(palette: dict) -> str:
    """Render Firefox's opt-in browser chrome without styling web pages."""
    roles = resolved_roles(palette)
    typography = palette["typography"]
    geometry = palette["geometry"]

    return f'''/* Generated by scripts/render_theme.py from assets/nighthowler/palette.toml.
 * Firefox userChrome.css is an unsupported upstream customization surface.
 * Cassan keeps selectors conservative so a Firefox update fails softly.
 */

:root {{
  --cassan-background: {roles["background"]};
  --cassan-panel: {roles["panel"]};
  --cassan-panel-alt: {roles["panel_alternate"]};
  --cassan-text: {roles["text"]};
  --cassan-text-secondary: {roles["text_secondary"]};
  --cassan-muted: {roles["text_muted"]};
  --cassan-focus: {roles["focus"]};
  --cassan-focus-inactive: {roles["focus_inactive"]};
  --toolbar-bgcolor: var(--cassan-panel) !important;
  --toolbar-color: var(--cassan-text) !important;
  --lwt-accent-color: var(--cassan-background) !important;
  --lwt-text-color: var(--cassan-text) !important;
  --toolbar-field-background-color: var(--cassan-panel-alt) !important;
  --toolbar-field-color: var(--cassan-text) !important;
  --toolbar-field-focus-background-color: var(--cassan-panel-alt) !important;
  --toolbar-field-focus-color: var(--cassan-text) !important;
  --toolbar-field-border-color: var(--cassan-focus-inactive) !important;
  --toolbar-field-focus-border-color: var(--cassan-focus) !important;
  --tab-selected-bgcolor: var(--cassan-focus) !important;
  --tab-selected-textcolor: var(--cassan-background) !important;
  --arrowpanel-background: var(--cassan-panel) !important;
  --arrowpanel-color: var(--cassan-text) !important;
  --arrowpanel-border-color: var(--cassan-focus-inactive) !important;
  --panel-separator-color: var(--cassan-panel-alt) !important;
  font-family: "{typography["desktop_font"]}" !important;
}}

#navigator-toolbox {{
  background: var(--cassan-panel) !important;
  border-bottom: {geometry["border_px"]}px solid var(--cassan-focus-inactive) !important;
}}

#TabsToolbar,
#nav-bar,
#PersonalToolbar {{
  background: var(--cassan-panel) !important;
  color: var(--cassan-text) !important;
}}

.tabbrowser-tab .tab-background,
#urlbar-background,
menupopup,
panel {{
  border-radius: {geometry["rounding_px"]}px !important;
}}

.tabbrowser-tab[selected] .tab-background {{
  background: var(--cassan-focus) !important;
  color: var(--cassan-background) !important;
}}

.tabbrowser-tab:not([selected]):hover .tab-background,
toolbarbutton:hover {{
  background: var(--cassan-panel-alt) !important;
}}

#urlbar-background {{
  background: var(--cassan-panel-alt) !important;
  border: 1px solid var(--cassan-focus-inactive) !important;
}}

#urlbar[focused] > #urlbar-background {{
  border-color: var(--cassan-focus) !important;
}}

menupopup,
panel {{
  --panel-background: var(--cassan-panel) !important;
  --panel-color: var(--cassan-text) !important;
  --panel-border-color: var(--cassan-focus-inactive) !important;
}}

::selection {{
  background: var(--cassan-focus) !important;
  color: var(--cassan-background) !important;
}}
'''


def render_firefox_content(palette: dict) -> str:
    """Render a restrained new-tab surface and leave ordinary sites untouched."""
    roles = resolved_roles(palette)
    typography = palette["typography"]
    geometry = palette["geometry"]

    return f'''/* Generated by scripts/render_theme.py from assets/nighthowler/palette.toml. */

@-moz-document url("about:home"), url("about:newtab"), url("about:blank") {{
  :root {{
    --newtab-background-color: {roles["background"]} !important;
    --newtab-background-color-secondary: {roles["panel"]} !important;
    --newtab-text-primary-color: {roles["text"]} !important;
    --newtab-text-secondary-color: {roles["text_secondary"]} !important;
    --newtab-primary-action-background: {roles["focus"]} !important;
    --newtab-primary-element-text-color: {roles["background"]} !important;
    --newtab-border-color: {roles["focus_inactive"]} !important;
  }}

  html,
  body {{
    background: {roles["background"]} !important;
    color: {roles["text"]} !important;
    font-family: "{typography["desktop_font"]}" !important;
  }}

  .search-handoff-button,
  .top-site-outer .tile,
  .card-outer {{
    background: {roles["panel"]} !important;
    border: 1px solid {roles["focus_inactive"]} !important;
    border-radius: {geometry["rounding_px"]}px !important;
    box-shadow: none !important;
  }}

  .top-site-outer:hover .tile,
  .card-outer:hover {{
    border-color: {roles["focus"]} !important;
  }}
}}
'''


def render_vesktop(palette: dict) -> str:
    """Render Vencord QuickCSS using Discord's semantic color variables."""
    colors = palette["colors"]
    roles = resolved_roles(palette)
    typography = palette["typography"]
    geometry = palette["geometry"]
    fast = palette["animation"]["duration_fast_ms"]

    return f'''/**
 * @name Cassan Nighthowler
 * @description Cassan's opaque violet desktop palette for Vesktop/Vencord.
 * @author Cassan
 * @version 1.0.0
 */

/* Generated by scripts/render_theme.py from assets/nighthowler/palette.toml.
 * No remote imports or assets are used.
 */

:root,
.theme-dark,
.theme-light {{
  --font-primary: "{typography["desktop_font"]}", monospace;
  --font-display: "{typography["desktop_font"]}", monospace;
  --background-primary: {roles["panel"]};
  --background-secondary: {roles["background"]};
  --background-secondary-alt: {roles["panel_alternate"]};
  --background-tertiary: {roles["background"]};
  --background-floating: {roles["panel_alternate"]};
  --background-base-lowest: {roles["background"]};
  --background-base-lower: {roles["background"]};
  --background-base-low: {roles["panel"]};
  --background-surface-high: {roles["panel_alternate"]};
  --background-surface-higher: {roles["panel_alternate"]};
  --background-modifier-hover: {roles["panel_alternate"]};
  --background-modifier-active: {roles["focus_inactive"]};
  --background-modifier-selected: {roles["focus_inactive"]};
  --channeltextarea-background: {roles["panel_alternate"]};
  --modal-background: {roles["panel"]};
  --modal-footer-background: {roles["background"]};
  --input-background: {roles["panel_alternate"]};
  --text-normal: {roles["text"]};
  --text-primary: {roles["text"]};
  --text-secondary: {roles["text_secondary"]};
  --text-muted: {roles["text_muted"]};
  --interactive-normal: {roles["text_secondary"]};
  --interactive-hover: {roles["text"]};
  --interactive-active: {roles["focus"]};
  --interactive-muted: {roles["text_muted"]};
  --channels-default: {roles["text_secondary"]};
  --channel-icon: {roles["text_muted"]};
  --brand-500: {roles["focus"]};
  --brand-560: {roles["focus_inactive"]};
  --brand-experiment: {roles["focus"]};
  --status-danger: {roles["urgent"]};
  --status-positive: {colors["sage"]};
  --status-warning: {roles["warm_accent"]};
}}

body,
button,
input,
textarea {{
  font-family: "{typography["desktop_font"]}", monospace !important;
}}

button,
input,
textarea,
[role="dialog"] {{
  border-radius: {geometry["rounding_px"]}px !important;
}}

[role="dialog"] {{
  border: {geometry["border_px"]}px solid {roles["focus_inactive"]};
}}

::selection {{
  background: {roles["focus"]};
  color: {roles["background"]};
}}

* {{
  scrollbar-color: {roles["focus_inactive"]} {roles["background"]};
}}

a,
button,
[role="button"] {{
  transition-duration: {fast}ms !important;
}}
'''


def render_spicetify_colors(palette: dict) -> str:
    """Render a Spicetify color scheme using its documented theme keys."""
    colors = palette["colors"]
    roles = resolved_roles(palette)
    value = lambda color: without_hash(color).lower()
    entries = {
        "text": roles["text"],
        "subtext": roles["text_muted"],
        "main": roles["background"],
        "main-elevated": roles["panel"],
        "main-transition": roles["background"],
        "highlight": roles["panel_alternate"],
        "highlight-elevated": roles["panel_alternate"],
        "sidebar": roles["panel"],
        "player": roles["panel"],
        "card": roles["panel_alternate"],
        "shadow": colors["forest"],
        "selected-row": roles["focus_inactive"],
        "button": roles["focus"],
        "button-active": colors["bright_orchid"],
        "button-disabled": roles["text_muted"],
        "tab-active": roles["focus_inactive"],
        "notification": colors["teal"],
        "notification-error": roles["urgent"],
        "misc": roles["warm_accent"],
        "play-button": roles["focus"],
        "play-button-active": colors["bright_orchid"],
        "progress-fg": roles["focus"],
        "progress-bg": roles["focus_inactive"],
        "heart": roles["urgent"],
        "pagelink-active": roles["focus"],
        "radio-btn-active": colors["teal"],
    }
    lines = [
        "; Generated by scripts/render_theme.py from assets/nighthowler/palette.toml.",
        "",
        "[Nighthowler]",
    ]
    lines.extend(f"{name:<20} = {value(color)}" for name, color in entries.items())
    lines.append("")
    return "\n".join(lines)


def render_spicetify_css(palette: dict) -> str:
    """Render restrained Spotify geometry on top of Spicetify's color map."""
    roles = resolved_roles(palette)
    typography = palette["typography"]
    geometry = palette["geometry"]
    fast = palette["animation"]["duration_fast_ms"]

    return f'''/* Generated by scripts/render_theme.py from assets/nighthowler/palette.toml. */

:root {{
  --cassan-panel: {roles["panel"]};
  --cassan-panel-alt: {roles["panel_alternate"]};
  --cassan-focus: {roles["focus"]};
  --cassan-focus-inactive: {roles["focus_inactive"]};
  --cassan-text: {roles["text"]};
  --cassan-muted: {roles["text_muted"]};
}}

body,
button,
input {{
  font-family: "{typography["desktop_font"]}", monospace !important;
}}

button,
input,
.main-card-card,
.main-trackList-trackListRow {{
  border-radius: {geometry["rounding_px"]}px !important;
}}

.main-navBar-navBar {{
  border-right: 1px solid var(--cassan-focus-inactive);
}}

.main-nowPlayingBar-nowPlayingBar {{
  border-top: {geometry["border_px"]}px solid var(--cassan-focus-inactive);
}}

.main-card-card {{
  border: 1px solid transparent;
  box-shadow: none !important;
  transition: border-color {fast}ms ease-out !important;
}}

.main-card-card:hover {{
  border-color: var(--cassan-focus);
}}

::selection {{
  background: var(--cassan-focus);
  color: {roles["background"]};
}}

* {{
  scrollbar-color: var(--cassan-focus-inactive) {roles["background"]};
}}
'''


def render_all() -> dict[Path, str]:
    validate_palette()
    palette = load(PALETTE_PATH)
    renderers = {
        "btop": render_btop,
        "cava": render_cava,
        "fastfetch": render_fastfetch,
        "firefox_chrome": render_firefox_chrome,
        "firefox_content": render_firefox_content,
        "hypr": render_hypr,
        "hyprlock": render_hyprlock,
        "hyprpaper": render_hyprpaper,
        "gtk": render_gtk_theme,
        "kitty": render_kitty,
        "swaync": render_swaync,
        "spicetify_colors": render_spicetify_colors,
        "spicetify_css": render_spicetify_css,
        "vesktop": render_vesktop,
        "wofi": render_wofi,
        "yazi": render_yazi,
    }
    return {path: renderers[renderer](palette) for path, renderer in OUTPUTS.items()}


def write_outputs(outputs: dict[Path, str]) -> None:
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"rendered {path.relative_to(REPO)}")


def check_outputs(outputs: dict[Path, str]) -> int:
    stale = []
    for path, expected in outputs.items():
        try:
            actual = path.read_text(encoding="utf-8")
        except FileNotFoundError:
            stale.append(path)
            continue
        if actual != expected:
            stale.append(path)

    if stale:
        for path in stale:
            print(f"stale generated theme: {path.relative_to(REPO)}", file=sys.stderr)
        print("run scripts/render_theme.py --write", file=sys.stderr)
        return 1

    print("Generated theme files are current.")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="verify committed outputs")
    mode.add_argument("--write", action="store_true", help="write component theme files")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    outputs = render_all()
    if args.write:
        write_outputs(outputs)
        return 0
    return check_outputs(outputs)


if __name__ == "__main__":
    raise SystemExit(main())
