#!/usr/bin/env python3

"""Render Cassan's shared palette into component-native theme files."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from validate_toml import PALETTE_PATH, REPO, load, validate_palette


OUTPUTS = {
    REPO / "hypr" / "theme.lua": "hypr",
    REPO / "hypr" / "hyprpaper.conf": "hyprpaper",
    REPO / "waybar" / "theme.css": "waybar",
}


def resolved_roles(palette: dict) -> dict[str, str]:
    colors = palette["colors"]
    return {name: colors[color_name] for name, color_name in palette["roles"].items()}


def without_hash(color: str) -> str:
    return color.removeprefix("#")


def alpha_hex(opacity: float) -> str:
    return f"{round(opacity * 255):02X}"


def lua_bool(value: bool) -> str:
    return str(value).lower()


def render_hypr(palette: dict) -> str:
    colors = palette["colors"]
    roles = resolved_roles(palette)
    typography = palette["typography"]
    geometry = palette["geometry"]
    animation = palette["animation"]

    lines = [
        "-- Generated by scripts/render_theme.py from assets/nighthowler/palette.toml.",
        "-- Do not edit this file directly.",
        "",
        "return {",
        f'  name = "{palette["name"]}",',
        f'  slug = "{palette["slug"]}",',
        "  colors = {",
    ]

    for name, value in sorted(colors.items()):
        if name == "transparent":
            continue
        lines.append(f'    {name} = "rgba({without_hash(value)}ff)",')

    lines.extend(["  },", "  roles = {"])
    for name, value in sorted(roles.items()):
        lines.append(f'    {name} = "rgba({without_hash(value)}ff)",')

    lines.extend(
        [
            "  },",
            "  geometry = {",
            f"    border = {geometry['border_px']},",
            f"    rounding = {geometry['rounding_px']},",
            f"    gaps_in = {geometry['gap_inner_px']},",
            f"    gaps_out = {geometry['gap_outer_px']},",
            f"    opacity = {geometry['opacity']},",
            f"    blur_enabled = {lua_bool(geometry['blur_enabled'])},",
            f"    shadow_enabled = {lua_bool(geometry['shadow_enabled'])},",
            f"    shadow_range = {geometry['shadow_blur_px']},",
            f"    shadow_opacity = {geometry['shadow_opacity']},",
            f'    shadow_color = "rgba(000000{alpha_hex(geometry["shadow_opacity"])})",',
            "  },",
            "  animation = {",
            f"    fast_ds = {animation['duration_fast_ms'] / 100},",
            f"    normal_ds = {animation['duration_normal_ms'] / 100},",
            f"    slow_ds = {animation['duration_slow_ms'] / 100},",
            "  },",
            "  typography = {",
            f'    desktop = "{typography["desktop_font"]}",',
            f'    terminal = "{typography["terminal_font"]}",',
            f"    bar_size = {typography['bar_size_px']},",
            "  },",
            "  wallpaper = {",
            f'    relative_path = "assets/{palette["slug"]}/{palette["wallpaper"]["filename"]}",',
            f'    fit_mode = "{palette["wallpaper"]["fit"]}",',
            "  },",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def render_hyprpaper(palette: dict) -> str:
    wallpaper = palette["wallpaper"]
    path = f'~/.config/cassan/assets/{palette["slug"]}/{wallpaper["filename"]}'
    return "\n".join(
        [
            "# Generated by scripts/render_theme.py from assets/nighthowler/palette.toml.",
            "# Do not edit this file directly.",
            "",
            "wallpaper {",
            "  monitor =",
            f"  path = {path}",
            f"  fit_mode = {wallpaper['fit']}",
            "}",
            "",
            "splash = false",
            "ipc = true",
            "",
        ]
    )


def render_waybar(palette: dict) -> str:
    colors = palette["colors"]
    roles = resolved_roles(palette)
    geometry = palette["geometry"]

    lines = [
        "/* Generated by scripts/render_theme.py from assets/nighthowler/palette.toml.",
        " * Do not edit this file directly.",
        " */",
        "",
    ]

    for name, value in sorted(colors.items()):
        css_name = name.replace("_", "-")
        lines.append(f"@define-color cassan-color-{css_name} {value};")

    lines.append("")
    for name, value in sorted(roles.items()):
        css_name = name.replace("_", "-")
        lines.append(f"@define-color cassan-{css_name} {value};")

    lines.extend(
        [
            f"@define-color cassan-shadow rgba(0, 0, 0, {geometry['shadow_opacity']});",
            "",
        ]
    )
    return "\n".join(lines)


def render_all() -> dict[Path, str]:
    validate_palette()
    palette = load(PALETTE_PATH)
    renderers = {
        "hypr": render_hypr,
        "hyprpaper": render_hyprpaper,
        "waybar": render_waybar,
    }
    return {path: renderers[renderer](palette) for path, renderer in OUTPUTS.items()}


def write_outputs(outputs: dict[Path, str]) -> None:
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"rendered {path.relative_to(REPO)}")


def check_outputs(outputs: dict[Path, str]) -> int:
    stale = []
    for path, expected in outputs.items():
        try:
            actual = path.read_text(encoding="utf-8")
        except FileNotFoundError:
            stale.append(path)
            continue
        if actual != expected:
            stale.append(path)

    if stale:
        for path in stale:
            print(f"stale generated theme: {path.relative_to(REPO)}", file=sys.stderr)
        print("run scripts/render_theme.py --write", file=sys.stderr)
        return 1

    print("Generated theme files are current.")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="verify committed outputs")
    mode.add_argument("--write", action="store_true", help="write component theme files")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    outputs = render_all()
    if args.write:
        write_outputs(outputs)
        return 0
    return check_outputs(outputs)


if __name__ == "__main__":
    raise SystemExit(main())
